# 共通の設定
sakura_ssh_pass: "enter-ftp_pass"
sakura_host_name: "username.sakura.ne.jp"
sakura_user_name: "enter_sakura_user_name"
sakura_db_host: "mysqlxxx.db.sakura.ne.jp"
sakura_db_user: "enter_sakura_db_user"
sakura_db_pass: "enter_sakura_db_pass"

# cronの実行時間を設定
# この設定の場合、毎日0:30に実行される
cron_hour: 0
cron_minute: 30
# cronを設定する場合はtrue 必要ない場合はfalse
cron_enable: true

# WordPressの変数を設定
# 辞書配列として同様に設定を追加していけばサイトが作成されます。
wordpress_info:
  - setting_name: "本番環境"
    directory: "production"
    db_name: "user_name_production"
    db_prefix: "wp_production_"
    admin_user_name: "enter_admin_name"
    admin_password: "enter_admin_password"
    admin_mail: "test@example.com"
    site_url: "http://user_name.sakura.ne.jp/production"
    site_title: "WordPress　demo site production"
    extra_php: "define( 'DISALLOW_FILE_EDIT',true );"
    test_data: false
    search_replace: false
    plugins: []

  # - setting_name: "ステージング環境"
  #   directory: "staging"
  #   db_name: "user_name_staging"
  #   db_prefix: "wp_staging_"
  #   admin_user_name: "enter_admin_name"
  #   admin_password: "enter_admin_password"
  #   admin_mail: "test@example.com"
  #   site_url: "http://user_name.sakura.ne.jp/staging"
  #   site_title: "WordPress　demo site staging"
  #   extra_php: |
  #     define( 'WP_DEBUG', true );
  #     define( 'WP_DEBUG_LOG', true );
  #     define( 'DISALLOW_FILE_EDIT',true );
  #   test_data: false
  #   plugins:
  #     - show-current-template



# 本番、ステージング両方の環境に入るプラグイン
common_plugins: []
