xserver:
  hosts:
    default_server:
      ansible_host: "{{ xserver_host_name }}"
      ansible_user: "{{ xserver_user_name }}"
      ansible_port: 10022
      ansible_ssh_private_key_file: "{{ ssh_key_file_path }}"
      # pythonのsshモジュールを指定
      ansible_connection: paramiko
  vars:
    ansible_python_interpreter: /usr/local/bin/python
